name: "Frogbot Security Scan"

on:
  pull_request_target: 
    types: [opened, synchronize] # Triggers scan-pr flow for every opened/updated pull request
  push: # Triggers scan-repo flow for every push to the specified branches
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"   # The repository will be scanned once a day at 00:00 GMT.
  workflow_dispatch: # The repository will be scanned on demand

permissions:
  pull-requests: write
  contents: write
  security-events: write
  # [Mandatory If using OIDC authentication protocol instead of JF_ACCESS_TOKEN]
  id-token: write

jobs:
  frogbot-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # The repository scanning will be triggered periodically on the following branches.
        branch: ["master"]
    steps:
      - uses: jfrog/frogbot@v2
        env:
            JF_URL: ${{ vars.JF_URL }}
            JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            JF_GIT_BASE_BRANCH: ${{ matrix.branch }}    # For repository scan action
            JF_INSTALL_DEPS_CMD: npm i --legacy-peer-deps
            CI: true
            JFROG_CLI_LOG_LEVEL: DEBUG
        with:
            oidc-provider-name: guy-github
